name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run tests
      run: go test ./...

    - name: Build binaries
      run: |
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -o dist/wtree-linux-amd64
        GOOS=linux GOARCH=arm64 go build -o dist/wtree-linux-arm64
        GOOS=darwin GOARCH=amd64 go build -o dist/wtree-darwin-amd64
        GOOS=darwin GOARCH=arm64 go build -o dist/wtree-darwin-arm64
        GOOS=windows GOARCH=amd64 go build -o dist/wtree-windows-amd64.exe
        GOOS=windows GOARCH=arm64 go build -o dist/wtree-windows-arm64.exe

    - name: Create checksums
      run: |
        cd dist
        sha256sum * > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/wtree-*
          dist/checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false